[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2023-01"
path = "2023/01/main.rs"

[[bin]]
name = "2023-02"
path = "2023/02/main.rs"

[[bin]]
name = "2023-03"
path = "2023/03/main.rs"

[[bin]]
name = "2023-04"
path = "2023/04/main.rs"
